version: 2
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          command: |
            # log in to dockerhub
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin

            # log in to ghcr.io
            echo "$GITHUB_PAT" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

            # build image
            make build

            # publish to dockerhub
            make push

            # publish to ghcr.io
            docker tag wastrachan/bind:latest ghcr.io/wastrachan/bind:latest
            docker push ghcr.io/wastrachan/bind:latest

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 1,4"
          filters:
            branches:
              only: master
    jobs:
      - build
