version: 2
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # login to dockerhub
      - run: echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin

      # login to ghcr.io
      - run: echo "$GITHUB_PAT" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

      # build image
      - run: make build

      # publish to dockerhub
      - run: make push

      # publish to ghcr.io
      - run: |
          docker tag wastrachan/bind:latest ghcr.io/wastrachan/bind:latest
          docker push ghcr.io/wastrachan/bind:latest

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 1,4"
          filters:
            branches:
              only: master
    jobs:
      - build
